services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:80"
    env_file:
      - .env.stage
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:17
    container_name: database
    restart: always
    env_file:
      - .env.stage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: