// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OweMeApi.Data;

#nullable disable

namespace OweMeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611094718_ReplaceEnumsWithStrings")]
    partial class ReplaceEnumsWithStrings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OweMeApi.Data.Entities.FriendCode", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FriendCodes");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Friendship", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DebtorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreditorId");

                    b.HasIndex("DebtorId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DebtAdjustments");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayerId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("DebtPayments");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtPaymentStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("DebtPaymentStatusChanges");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.LedgerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentStatusChangeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("AdjustmentId")
                        .IsUnique();

                    b.HasIndex("DebtId");

                    b.HasIndex("InternalReference")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("PaymentStatusChangeId")
                        .IsUnique();

                    b.ToTable("LedgerEvents");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.UserRole", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Code = "ADMIN",
                            Label = "Administrator"
                        },
                        new
                        {
                            Code = "MODERATOR",
                            Label = "Moderator"
                        },
                        new
                        {
                            Code = "USER",
                            Label = "Użytkownik"
                        },
                        new
                        {
                            Code = "LOCKED",
                            Label = "Zablokowany"
                        });
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.FriendCode", b =>
                {
                    b.HasOne("OweMeApi.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("OweMeApi.Data.Entities.FriendCode", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Friendship", b =>
                {
                    b.HasOne("OweMeApi.Data.Entities.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OweMeApi.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.Debt", b =>
                {
                    b.HasOne("OweMeApi.Data.Entities.User", "Creditor")
                        .WithMany()
                        .HasForeignKey("CreditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OweMeApi.Data.Entities.User", "Debtor")
                        .WithMany()
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creditor");

                    b.Navigation("Debtor");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtPayment", b =>
                {
                    b.HasOne("OweMeApi.Data.Entities.User", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OweMeApi.Data.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtPaymentStatusChange", b =>
                {
                    b.HasOne("OweMeApi.Data.Entities.Ledger.DebtPayment", "Payment")
                        .WithMany("StatusChanges")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.LedgerEvent", b =>
                {
                    b.HasOne("OweMeApi.Data.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OweMeApi.Data.Entities.Ledger.DebtAdjustment", "Adjustment")
                        .WithOne("LedgerEvent")
                        .HasForeignKey("OweMeApi.Data.Entities.Ledger.LedgerEvent", "AdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OweMeApi.Data.Entities.Ledger.Debt", "Debt")
                        .WithMany("LedgerEvents")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OweMeApi.Data.Entities.Ledger.DebtPayment", "Payment")
                        .WithOne("LedgerEvent")
                        .HasForeignKey("OweMeApi.Data.Entities.Ledger.LedgerEvent", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OweMeApi.Data.Entities.Ledger.DebtPaymentStatusChange", "PaymentStatusChange")
                        .WithOne("LedgerEvent")
                        .HasForeignKey("OweMeApi.Data.Entities.Ledger.LedgerEvent", "PaymentStatusChangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Actor");

                    b.Navigation("Adjustment");

                    b.Navigation("Debt");

                    b.Navigation("Payment");

                    b.Navigation("PaymentStatusChange");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.User", b =>
                {
                    b.HasOne("OweMeApi.Data.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.Debt", b =>
                {
                    b.Navigation("LedgerEvents");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtAdjustment", b =>
                {
                    b.Navigation("LedgerEvent")
                        .IsRequired();
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtPayment", b =>
                {
                    b.Navigation("LedgerEvent")
                        .IsRequired();

                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("OweMeApi.Data.Entities.Ledger.DebtPaymentStatusChange", b =>
                {
                    b.Navigation("LedgerEvent")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
